In [104]:
import pandas as pd
import numpy as np
import torch

In [81]:
training = pd.read_csv("data/credit-card-train.csv")
y = training["IsFraud"]
exclude_columns = ["id", "Time", "Transaction_Amount", "IsFraud"]

clean_training = training.drop(exclude_columns, axis = 1)

In [217]:
# Function that takes in a df and ramdomly replaces n features per row with `value`
# If random variable in value, then set random = True so a random variable will be used instead 

def create_random(n):
    return torch.tensor(np.random.normal(loc = 0, scale = 1000000, size = n)).float()

# Masking df with given value 
def mask_features(df, n, value, random):
    df_copy = df.clone()
    
    for index, row in enumerate(df_copy):
        idx = torch.randperm(row.size(0))[:n]
        print(idx)
        if random == True:
            row[idx] = create_random(n = n)
        else: 
            row[idx] = value
        
    return df_copy

subset = clean_training.iloc[0:5]
subset = torch.tensor(subset.values).float()

random_mask_df = mask_features(df = subset, n = 5, random = False, value = 9999)
random_mask_df

tensor([20, 13, 25,  8, 14])
tensor([18, 12, 19, 21, 25])
tensor([ 2, 17,  7,  8,  0])
tensor([15, 20, 22,  7, 25])
tensor([19, 26,  3, 14, 16])


tensor([[ 2.0743e+00, -1.2943e-01, -1.1374e+00,  4.1285e-01, -1.9264e-01,
         -1.2101e+00,  1.1070e-01, -2.6348e-01,  9.9990e+03,  1.0878e-01,
         -1.0702e+00, -2.3491e-01, -1.0994e+00,  9.9990e+03,  9.9990e+03,
          6.5688e-02, -3.0696e-01, -3.2380e-01,  1.0335e-01, -2.9297e-01,
          9.9990e+03, -8.8784e-01,  3.3670e-01, -1.1083e-01, -2.9146e-01,
          9.9990e+03, -7.6576e-02, -5.9577e-02],
        [ 1.9988e+00, -1.2509e+00, -5.2097e-01, -8.9454e-01, -1.1225e+00,
         -2.7087e-01, -1.0293e+00,  5.0198e-02, -1.0995e-01,  9.0877e-01,
          8.3680e-01, -5.6580e-02,  9.9990e+03, -1.4403e-01, -3.9582e-02,
          1.6531e+00, -2.5360e-01, -8.1435e-01,  9.9990e+03,  9.9990e+03,
          5.4848e-02,  9.9990e+03,  1.3352e-01, -4.6193e-01, -4.6549e-01,
          9.9990e+03, -9.4127e-03, -3.8238e-02],
        [ 9.9990e+03,  1.0045e+00,  9.9990e+03, -4.3525e-01,  6.6755e-01,
         -9.8835e-01,  9.4815e-01,  9.9990e+03,  9.9990e+03, -8.1838e-01,
         -3.76